<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 static/assets/models/pond/scene.gltf
Author: CrypticKoi (https://sketchfab.com/CrypticKoi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/japanese-pond-diorama-85c2c68dcb6c4b5b8cbbcdfe34a6f7c6
Title: Japanese Pond Diorama
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('assets/models/pond/scene.gltf')
  export const { actions, mixer } = useGltfAnimations(gltf, ref)

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Sketchfab_Scene">
      <T.Group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
        <T.Group name="33e6502e263e49b190f3594d51516be7fbx" rotation={[Math.PI / 2, 0, 0]}>
          <T.Group name="Object_2">
            <T.Group name="RootNode">
              <T.Group
                name="Lantern4"
                position={[-6.12, 31.37, -0.02]}
                rotation={[-3.08, 0, 0.05]}
                scale={[0.6, 0.17, 0.6]}
              >
                <T.Group name="Lantern2pSphere3" position={[-0.1, 56.42, -0.34]}>
                  <T.Mesh
                    name="Lantern2pSphere3_Lantern2StingrayPBS1_0"
                    geometry={gltf.nodes.Lantern2pSphere3_Lantern2StingrayPBS1_0.geometry}
                    material={gltf.materials.Lantern2StingrayPBS1}
                  />
                </T.Group>
                <T.Group
                  name="Lantern2pCylinder3"
                  position={[-0.1, 52.67, -0.32]}
                  rotation={[3.14, 0, 0]}
                  scale={[0.03, 3.66, 0.03]}
                >
                  <T.Mesh
                    name="Lantern2pCylinder3_Lantern2StingrayPBS1_0"
                    geometry={gltf.nodes.Lantern2pCylinder3_Lantern2StingrayPBS1_0.geometry}
                    material={gltf.materials.Lantern2StingrayPBS1}
                  />
                </T.Group>
                <T.Group name="Lantern2pCylinder2" position={[-0.1, 49.26, -0.3]}>
                  <T.Mesh
                    name="Lantern2pCylinder2_Lantern2StingrayPBS1_0"
                    geometry={gltf.nodes.Lantern2pCylinder2_Lantern2StingrayPBS1_0.geometry}
                    material={gltf.materials.Lantern2StingrayPBS1}
                  />
                </T.Group>
                <T.Group
                  name="pointLight1"
                  position={[0.38, 35.04, 8.09]}
                  rotation={[3.14, 0, 0]}
                  scale={[2.71, 9.51, 2.71]}
                >
                  <T.Group name="Object_342" rotation={[Math.PI / 2, 0, 0]}>
                    <T.Group name="Object_343" />
                  </T.Group>
                </T.Group>
                <T.Group
                  name="Lantern2pSphere2"
                  position={[-0.1, 39.66, -0.25]}
                  rotation={[3.14, 0, 0]}
                  scale={[2.71, 9.51, 2.71]}
                >
                  <T.Mesh
                    name="Lantern2pSphere2_lambert1_0"
                    geometry={gltf.nodes.Lantern2pSphere2_lambert1_0.geometry}
                    material={gltf.materials.lambert1}
                  />
                </T.Group>
                <T.Group
                  name="pCylinder3"
                  position={[-0.1, 15.05, -0.12]}
                  rotation={[3.14, 0, 0]}
                  scale={[0.03, 14.89, 0.03]}
                >
                  <T.Mesh
                    name="pCylinder3_Lantern2StingrayPBS1_0"
                    geometry={gltf.nodes.pCylinder3_Lantern2StingrayPBS1_0.geometry}
                    material={gltf.materials.Lantern2StingrayPBS1}
                  />
                </T.Group>
                <T.Mesh
                  name="Lantern4_Lantern2StingrayPBS1_0"
                  geometry={gltf.nodes.Lantern4_Lantern2StingrayPBS1_0.geometry}
                  material={gltf.materials.Lantern2StingrayPBS1}
                />
              </T.Group>
              <T.Group
                name="Lantern5"
                position={[-16.75, 35.69, 19.89]}
                rotation={[-0.02, 0.1, -3.03]}
                scale={[0.6, 0.17, 0.6]}
              >
                <T.Group name="pSphere3" position={[0.23, 46.44, -0.19]}>
                  <T.Mesh
                    name="pSphere3_Lantern2StingrayPBS1_0"
                    geometry={gltf.nodes.pSphere3_Lantern2StingrayPBS1_0.geometry}
                    material={gltf.materials.Lantern2StingrayPBS1}
                  />
                </T.Group>
                <T.Group
                  name="pCylinder3_1"
                  position={[0.23, 42.69, -0.17]}
                  rotation={[3.14, 0, 0]}
                  scale={[0.03, 3.66, 0.03]}
                >
                  <T.Mesh
                    name="pCylinder3_Lantern2StingrayPBS1_0_1"
                    geometry={gltf.nodes.pCylinder3_Lantern2StingrayPBS1_0_1.geometry}
                    material={gltf.materials.Lantern2StingrayPBS1}
                  />
                </T.Group>
                <T.Group name="pCylinder2" position={[0.23, 39.28, -0.15]}>
                  <T.Mesh
                    name="pCylinder2_Lantern2StingrayPBS1_0"
                    geometry={gltf.nodes.pCylinder2_Lantern2StingrayPBS1_0.geometry}
                    material={gltf.materials.Lantern2StingrayPBS1}
                  />
                </T.Group>
                <T.Group
                  name="pSphere2"
                  position={[-0.08, 2.87, -0.04]}
                  rotation={[3.14, 0, 0]}
                  scale={[2.71, 9.51, 2.71]}
                >
                  <T.Mesh
                    name="pSphere2_lambert1_0"
                    geometry={gltf.nodes.pSphere2_lambert1_0.geometry}
                    material={gltf.materials.lambert1}
                  />
                </T.Group>
                <T.Group
                  name="pCylinder13"
                  position={[0.25, 12.41, -0.03]}
                  rotation={[3.14, 0, 0]}
                  scale={[0.03, 7.38, 0.03]}
                >
                  <T.Mesh
                    name="pCylinder13_Lantern2StingrayPBS1_0"
                    geometry={gltf.nodes.pCylinder13_Lantern2StingrayPBS1_0.geometry}
                    material={gltf.materials.Lantern2StingrayPBS1}
                  />
                </T.Group>
                <T.Mesh
                  name="Lantern5_Lantern2StingrayPBS1_0"
                  geometry={gltf.nodes.Lantern5_Lantern2StingrayPBS1_0.geometry}
                  material={gltf.materials.Lantern2StingrayPBS1}
                />
              </T.Group>
              <T.Group
                name="Lantern3"
                position={[-6.21, 33.39, -9.22]}
                rotation={[0.03, 0.1, 3.12]}
                scale={[0.6, 0.17, 0.6]}
              >
                <T.Group name="pSphere3_1" position={[-0.04, 39.09, 0.03]}>
                  <T.Mesh
                    name="pSphere3_Lantern2StingrayPBS1_0_1"
                    geometry={gltf.nodes.pSphere3_Lantern2StingrayPBS1_0_1.geometry}
                    material={gltf.materials.Lantern2StingrayPBS1}
                  />
                </T.Group>
                <T.Group
                  name="pCylinder3_2"
                  position={[-0.04, 35.34, 0.05]}
                  rotation={[3.14, 0, 0]}
                  scale={[0.03, 3.66, 0.03]}
                >
                  <T.Mesh
                    name="pCylinder3_Lantern2StingrayPBS1_0_2"
                    geometry={gltf.nodes.pCylinder3_Lantern2StingrayPBS1_0_2.geometry}
                    material={gltf.materials.Lantern2StingrayPBS1}
                  />
                </T.Group>
                <T.Group name="pCylinder2_1" position={[-0.04, 31.93, 0.07]}>
                  <T.Mesh
                    name="pCylinder2_Lantern2StingrayPBS1_0_1"
                    geometry={gltf.nodes.pCylinder2_Lantern2StingrayPBS1_0_1.geometry}
                    material={gltf.materials.Lantern2StingrayPBS1}
                  />
                </T.Group>
                <T.Group
                  name="pSphere2_1"
                  position={[-0.04, 22.33, 0.12]}
                  rotation={[3.14, 0, 0]}
                  scale={[2.71, 9.51, 2.71]}
                >
                  <T.Mesh
                    name="pSphere2_lambert1_0_1"
                    geometry={gltf.nodes.pSphere2_lambert1_0_1.geometry}
                    material={gltf.materials.lambert1}
                  />
                </T.Group>
                <T.Group
                  name="pCylinder13_1"
                  position={[-0.02, 5.06, 0.18]}
                  rotation={[3.14, 0, 0]}
                  scale={[0.03, 7.38, 0.03]}
                >
                  <T.Mesh
                    name="pCylinder13_Lantern2StingrayPBS1_0_1"
                    geometry={gltf.nodes.pCylinder13_Lantern2StingrayPBS1_0_1.geometry}
                    material={gltf.materials.Lantern2StingrayPBS1}
                  />
                </T.Group>
                <T.Group
                  name="pointLight2"
                  position={[-11, 30.44, 47.56]}
                  rotation={[0.01, 0.1, 3.14]}
                  scale={[2.71, 9.51, 2.71]}
                >
                  <T.Group name="Object_415" rotation={[Math.PI / 2, 0, 0]}>
                    <T.Group name="Object_416" />
                  </T.Group>
                </T.Group>
                <T.Mesh
                  name="Lantern3_Lantern2StingrayPBS1_0"
                  geometry={gltf.nodes.Lantern3_Lantern2StingrayPBS1_0.geometry}
                  material={gltf.materials.Lantern2StingrayPBS1}
                />
              </T.Group>
              <T.Group
                name="Lantern6"
                position={[3.05, 35.12, 18.39]}
                rotation={[0.04, 0.1, 3.07]}
                scale={[0.6, 0.17, 0.6]}
              >
                <T.Group name="pSphere3_2" position={[0.18, 41.64, -0.18]}>
                  <T.Mesh
                    name="pSphere3_Lantern2StingrayPBS1_0_2"
                    geometry={gltf.nodes.pSphere3_Lantern2StingrayPBS1_0_2.geometry}
                    material={gltf.materials.Lantern2StingrayPBS1}
                  />
                </T.Group>
                <T.Group
                  name="pCylinder3_3"
                  position={[0.18, 37.89, -0.16]}
                  rotation={[3.14, 0, 0]}
                  scale={[0.03, 3.66, 0.03]}
                >
                  <T.Mesh
                    name="pCylinder3_Lantern2StingrayPBS1_0_3"
                    geometry={gltf.nodes.pCylinder3_Lantern2StingrayPBS1_0_3.geometry}
                    material={gltf.materials.Lantern2StingrayPBS1}
                  />
                </T.Group>
                <T.Group name="pCylinder2_2" position={[0.18, 34.48, -0.14]}>
                  <T.Mesh
                    name="pCylinder2_Lantern2StingrayPBS1_0_2"
                    geometry={gltf.nodes.pCylinder2_Lantern2StingrayPBS1_0_2.geometry}
                    material={gltf.materials.Lantern2StingrayPBS1}
                  />
                </T.Group>
                <T.Group
                  name="pSphere2_2"
                  position={[0.18, 24.88, -0.09]}
                  rotation={[3.14, 0, 0]}
                  scale={[2.71, 9.51, 2.71]}
                >
                  <T.Mesh
                    name="pSphere2_lambert1_0_2"
                    geometry={gltf.nodes.pSphere2_lambert1_0_2.geometry}
                    material={gltf.materials.lambert1}
                  />
                </T.Group>
                <T.Group
                  name="pCylinder13_2"
                  position={[0.19, 7.6, -0.02]}
                  rotation={[3.14, 0, 0]}
                  scale={[0.03, 7.38, 0.03]}
                >
                  <T.Mesh
                    name="pCylinder13_Lantern2StingrayPBS1_0_2"
                    geometry={gltf.nodes.pCylinder13_Lantern2StingrayPBS1_0_2.geometry}
                    material={gltf.materials.Lantern2StingrayPBS1}
                  />
                </T.Group>
                <T.Group
                  name="pointLight3"
                  position={[36.55, 47.31, -1.19]}
                  rotation={[0.01, 0.1, 3.14]}
                  scale={[2.71, 9.51, 2.71]}
                >
                  <T.Group name="Object_430" rotation={[Math.PI / 2, 0, 0]}>
                    <T.Group name="Object_431" />
                  </T.Group>
                </T.Group>
                <T.Mesh
                  name="Lantern6_Lantern2StingrayPBS1_0"
                  geometry={gltf.nodes.Lantern6_Lantern2StingrayPBS1_0.geometry}
                  material={gltf.materials.Lantern2StingrayPBS1}
                />
              </T.Group>
              <T.Group
                name="TreepCylinder1"
                position={[-11.53, 17.08, 16.84]}
                rotation={[3.05, -0.68, 3.05]}
                scale={[4.67, 7.3, 4.94]}
              >
                <T.Group
                  name="TreepCube3"
                  position={[0.83, 4.27, 0]}
                  rotation={[3.14, 0.01, 3.12]}
                  scale={[0.43, 0.43, 0.8]}
                >
                  <T.Mesh
                    name="TreepCube3_StingrayPBS4_0"
                    geometry={gltf.nodes.TreepCube3_StingrayPBS4_0.geometry}
                    material={gltf.materials.StingrayPBS4}
                  />
                </T.Group>
                <T.Group
                  name="pCube3"
                  position={[5.76, 2.53, -0.04]}
                  rotation={[3.14, 0.01, 3.12]}
                  scale={[1.05, 0.59, 0.93]}
                >
                  <T.Group
                    name="pCube18"
                    position={[4.03, 2.37, -0.16]}
                    rotation={[-1.79, 0.93, 0.16]}
                    scale={[0.41, 0.39, 0.49]}
                  >
                    <T.Mesh
                      name="pCube18_StingrayPBS4_0"
                      geometry={gltf.nodes.pCube18_StingrayPBS4_0.geometry}
                      material={gltf.materials.StingrayPBS4}
                    />
                  </T.Group>
                  <T.Group
                    name="pCube17"
                    position={[2.83, 0.19, 1.64]}
                    rotation={[0.01, 0.61, -0.01]}
                    scale={[0.39, 0.42, 0.48]}
                  >
                    <T.Mesh
                      name="pCube17_StingrayPBS4_0"
                      geometry={gltf.nodes.pCube17_StingrayPBS4_0.geometry}
                      material={gltf.materials.StingrayPBS4}
                    />
                  </T.Group>
                  <T.Mesh
                    name="pCube3_StingrayPBS4_0"
                    geometry={gltf.nodes.pCube3_StingrayPBS4_0.geometry}
                    material={gltf.materials.StingrayPBS4}
                  />
                </T.Group>
                <T.Group
                  name="pCube19"
                  position={[-7.91, 4.07, -2.31]}
                  rotation={[0.08, -0.41, -0.08]}
                  scale={[0.81, 0.45, 0.72]}
                >
                  <T.Group
                    name="pCube18_1"
                    position={[4.03, 2.37, -0.16]}
                    rotation={[-1.79, 0.93, 0.16]}
                    scale={[0.41, 0.39, 0.49]}
                  >
                    <T.Mesh
                      name="pCube18_StingrayPBS4_0_1"
                      geometry={gltf.nodes.pCube18_StingrayPBS4_0_1.geometry}
                      material={gltf.materials.StingrayPBS4}
                    />
                  </T.Group>
                  <T.Group
                    name="pCube17_1"
                    position={[2.83, 0.19, 1.64]}
                    rotation={[0.01, 0.61, -0.01]}
                    scale={[0.39, 0.42, 0.48]}
                  >
                    <T.Mesh
                      name="pCube17_StingrayPBS4_0_1"
                      geometry={gltf.nodes.pCube17_StingrayPBS4_0_1.geometry}
                      material={gltf.materials.StingrayPBS4}
                    />
                  </T.Group>
                  <T.Mesh
                    name="pCube19_StingrayPBS4_0"
                    geometry={gltf.nodes.pCube19_StingrayPBS4_0.geometry}
                    material={gltf.materials.StingrayPBS4}
                  />
                </T.Group>
                <T.Group
                  name="pCube20"
                  position={[-2.56, 1.84, -4.97]}
                  rotation={[1.13, -1.26, 1.24]}
                  scale={[0.67, 0.59, 0.93]}
                >
                  <T.Group
                    name="pCube18_2"
                    position={[4.03, 2.37, -0.16]}
                    rotation={[-1.79, 0.93, 0.16]}
                    scale={[0.41, 0.39, 0.49]}
                  >
                    <T.Mesh
                      name="pCube18_StingrayPBS4_0_2"
                      geometry={gltf.nodes.pCube18_StingrayPBS4_0_2.geometry}
                      material={gltf.materials.StingrayPBS4}
                    />
                  </T.Group>
                  <T.Group
                    name="pCube17_2"
                    position={[2.83, 0.19, 1.64]}
                    rotation={[0.01, 0.61, -0.01]}
                    scale={[0.39, 0.42, 0.48]}
                  >
                    <T.Mesh
                      name="pCube17_StingrayPBS4_0_2"
                      geometry={gltf.nodes.pCube17_StingrayPBS4_0_2.geometry}
                      material={gltf.materials.StingrayPBS4}
                    />
                  </T.Group>
                  <T.Mesh
                    name="pCube20_StingrayPBS4_0"
                    geometry={gltf.nodes.pCube20_StingrayPBS4_0.geometry}
                    material={gltf.materials.StingrayPBS4}
                  />
                </T.Group>
                <T.Group
                  name="pCube21"
                  position={[-2.8, 2.94, 3.31]}
                  rotation={[-0.11, 1.4, 0.11]}
                  scale={[0.43, 0.43, 0.8]}
                >
                  <T.Mesh
                    name="pCube21_StingrayPBS4_0"
                    geometry={gltf.nodes.pCube21_StingrayPBS4_0.geometry}
                    material={gltf.materials.StingrayPBS4}
                  />
                </T.Group>
                <T.Group
                  name="pCube22"
                  position={[-6.86, 2.02, 6.21]}
                  rotation={[-0.03, 0.9, 0.03]}
                  scale={[1.05, 0.59, 0.93]}
                >
                  <T.Group
                    name="pCube18_3"
                    position={[4.03, 2.37, -0.16]}
                    rotation={[-1.79, 0.93, 0.16]}
                    scale={[0.41, 0.39, 0.49]}
                  >
                    <T.Mesh
                      name="pCube18_StingrayPBS4_0_3"
                      geometry={gltf.nodes.pCube18_StingrayPBS4_0_3.geometry}
                      material={gltf.materials.StingrayPBS4}
                    />
                  </T.Group>
                  <T.Group
                    name="pCube17_3"
                    position={[2.83, 0.19, 1.64]}
                    rotation={[0.01, 0.61, -0.01]}
                    scale={[0.39, 0.42, 0.48]}
                  >
                    <T.Mesh
                      name="pCube17_StingrayPBS4_0_3"
                      geometry={gltf.nodes.pCube17_StingrayPBS4_0_3.geometry}
                      material={gltf.materials.StingrayPBS4}
                    />
                  </T.Group>
                  <T.Mesh
                    name="pCube22_StingrayPBS4_0"
                    geometry={gltf.nodes.pCube22_StingrayPBS4_0.geometry}
                    material={gltf.materials.StingrayPBS4}
                  />
                </T.Group>
                <T.Group
                  name="pCube23"
                  position={[-1.27, 5.88, -0.02]}
                  rotation={[3.14, 0.01, 2.66]}
                  scale={[0.19, 0.19, 0.35]}
                >
                  <T.Mesh
                    name="pCube23_StingrayPBS4_0"
                    geometry={gltf.nodes.pCube23_StingrayPBS4_0.geometry}
                    material={gltf.materials.StingrayPBS4}
                  />
                </T.Group>
                <T.Mesh
                  name="TreepCylinder1_StingrayPBS4_0"
                  geometry={gltf.nodes.TreepCylinder1_StingrayPBS4_0.geometry}
                  material={gltf.materials.StingrayPBS4}
                />
              </T.Group>
              <T.Group name="pPlane1" position={[12.37, -1.47, 0]} scale={[214.54, 215.14, 214.54]}>
                <T.Group name="pPlane2" position={[0.26, 0, 0]} scale={0.04}>
                  <T.Mesh
                    name="pPlane2_lambert3_0"
                    geometry={gltf.nodes.pPlane2_lambert3_0.geometry}
                    material={gltf.materials.lambert3}
                  />
                </T.Group>
                <T.Group name="pPlane3" position={[-0.23, 0, 0]} scale={0.04}>
                  <T.Mesh
                    name="pPlane3_lambert3_0"
                    geometry={gltf.nodes.pPlane3_lambert3_0.geometry}
                    material={gltf.materials.lambert3}
                  />
                </T.Group>
                <T.Group name="pPlane4" position={[-0.23, 0, 0.16]} rotation={[-0.05, 1.04, 0.03]} scale={0.04}>
                  <T.Mesh
                    name="pPlane4_lambert3_0"
                    geometry={gltf.nodes.pPlane4_lambert3_0.geometry}
                    material={gltf.materials.lambert3}
                  />
                </T.Group>
                <T.Group name="pPlane5" position={[-0.19, 0, 0.18]} rotation={[-3.12, 0.62, 3.07]} scale={0.04}>
                  <T.Mesh
                    name="pPlane5_lambert3_0"
                    geometry={gltf.nodes.pPlane5_lambert3_0.geometry}
                    material={gltf.materials.lambert3}
                  />
                </T.Group>
                <T.Group name="pPlane6" position={[-0.23, 0, 0.08]} scale={0.06}>
                  <T.Mesh
                    name="pPlane6_lambert3_0"
                    geometry={gltf.nodes.pPlane6_lambert3_0.geometry}
                    material={gltf.materials.lambert3}
                  />
                </T.Group>
                <T.Group name="pPlane18" position={[-0.21, 0, 0.04]} rotation={[0, 0.71, 0]} scale={0.06}>
                  <T.Mesh
                    name="pPlane18_lambert3_0"
                    geometry={gltf.nodes.pPlane18_lambert3_0.geometry}
                    material={gltf.materials.lambert3}
                  />
                </T.Group>
                <T.Mesh
                  name="pPlane1_lambert2_0"
                  geometry={gltf.nodes.pPlane1_lambert2_0.geometry}
                  material={gltf.materials.lambert2}
                />
              </T.Group>
              <T.Group name="Island_1" position={[9.53, 0, 17.59]} rotation={[0, 1.16, 0]} scale={[29.51, 8.58, 49.35]}>
                <T.Mesh
                  name="Island_1_StingrayPBS2_0"
                  geometry={gltf.nodes.Island_1_StingrayPBS2_0.geometry}
                  material={gltf.materials.StingrayPBS2}
                />
              </T.Group>
              <T.Group name="BridgeBridge">
                <T.Group name="BridgePole1">
                  <T.Group name="BridgepSphere1">
                    <T.Mesh
                      name="BridgepSphere1_BridgeStingrayPBS1_0"
                      geometry={gltf.nodes.BridgepSphere1_BridgeStingrayPBS1_0.geometry}
                      material={gltf.materials.BridgeStingrayPBS1}
                    />
                  </T.Group>
                  <T.Mesh
                    name="BridgePole1_BridgeStingrayPBS1_0"
                    geometry={gltf.nodes.BridgePole1_BridgeStingrayPBS1_0.geometry}
                    material={gltf.materials.BridgeStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="BridgePole4">
                  <T.Group name="BridgepSphere1_1">
                    <T.Mesh
                      name="BridgepSphere1_BridgeStingrayPBS1_0_1"
                      geometry={gltf.nodes.BridgepSphere1_BridgeStingrayPBS1_0_1.geometry}
                      material={gltf.materials.BridgeStingrayPBS1}
                    />
                  </T.Group>
                  <T.Mesh
                    name="BridgePole4_BridgeStingrayPBS1_0"
                    geometry={gltf.nodes.BridgePole4_BridgeStingrayPBS1_0.geometry}
                    material={gltf.materials.BridgeStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="BridgePole5">
                  <T.Group name="BridgepSphere1_2">
                    <T.Mesh
                      name="BridgepSphere1_BridgeStingrayPBS1_0_2"
                      geometry={gltf.nodes.BridgepSphere1_BridgeStingrayPBS1_0_2.geometry}
                      material={gltf.materials.BridgeStingrayPBS1}
                    />
                  </T.Group>
                  <T.Mesh
                    name="BridgePole5_BridgeStingrayPBS1_0"
                    geometry={gltf.nodes.BridgePole5_BridgeStingrayPBS1_0.geometry}
                    material={gltf.materials.BridgeStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="BridgePole6">
                  <T.Group name="BridgepSphere1_3">
                    <T.Mesh
                      name="BridgepSphere1_BridgeStingrayPBS1_0_3"
                      geometry={gltf.nodes.BridgepSphere1_BridgeStingrayPBS1_0_3.geometry}
                      material={gltf.materials.BridgeStingrayPBS1}
                    />
                  </T.Group>
                  <T.Mesh
                    name="BridgePole6_BridgeStingrayPBS1_0"
                    geometry={gltf.nodes.BridgePole6_BridgeStingrayPBS1_0.geometry}
                    material={gltf.materials.BridgeStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="BridgeBottom2">
                  <T.Mesh
                    name="BridgeBottom2_BridgeStingrayPBS2_0"
                    geometry={gltf.nodes.BridgeBottom2_BridgeStingrayPBS2_0.geometry}
                    material={gltf.materials.BridgeStingrayPBS2}
                  />
                </T.Group>
                <T.Group name="BridgeBottom3">
                  <T.Mesh
                    name="BridgeBottom3_BridgeStingrayPBS2_0"
                    geometry={gltf.nodes.BridgeBottom3_BridgeStingrayPBS2_0.geometry}
                    material={gltf.materials.BridgeStingrayPBS2}
                  />
                </T.Group>
                <T.Group name="BridgepCube20">
                  <T.Mesh
                    name="BridgepCube20_BridgeStingrayPBS1_0"
                    geometry={gltf.nodes.BridgepCube20_BridgeStingrayPBS1_0.geometry}
                    material={gltf.materials.BridgeStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="BridgepCube19">
                  <T.Mesh
                    name="BridgepCube19_BridgeStingrayPBS1_0"
                    geometry={gltf.nodes.BridgepCube19_BridgeStingrayPBS1_0.geometry}
                    material={gltf.materials.BridgeStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="BridgepCube18">
                  <T.Mesh
                    name="BridgepCube18_BridgeStingrayPBS1_0"
                    geometry={gltf.nodes.BridgepCube18_BridgeStingrayPBS1_0.geometry}
                    material={gltf.materials.BridgeStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="BridgepCube17">
                  <T.Mesh
                    name="BridgepCube17_BridgeStingrayPBS1_0"
                    geometry={gltf.nodes.BridgepCube17_BridgeStingrayPBS1_0.geometry}
                    material={gltf.materials.BridgeStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="BridgepCube16">
                  <T.Mesh
                    name="BridgepCube16_BridgeStingrayPBS1_0"
                    geometry={gltf.nodes.BridgepCube16_BridgeStingrayPBS1_0.geometry}
                    material={gltf.materials.BridgeStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="BridgepCube15">
                  <T.Mesh
                    name="BridgepCube15_BridgeStingrayPBS1_0"
                    geometry={gltf.nodes.BridgepCube15_BridgeStingrayPBS1_0.geometry}
                    material={gltf.materials.BridgeStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="BridgepCube14">
                  <T.Mesh
                    name="BridgepCube14_BridgeStingrayPBS1_0"
                    geometry={gltf.nodes.BridgepCube14_BridgeStingrayPBS1_0.geometry}
                    material={gltf.materials.BridgeStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="BridgepCube13">
                  <T.Mesh
                    name="BridgepCube13_BridgeStingrayPBS1_0"
                    geometry={gltf.nodes.BridgepCube13_BridgeStingrayPBS1_0.geometry}
                    material={gltf.materials.BridgeStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="BridgepCube12">
                  <T.Mesh
                    name="BridgepCube12_BridgeStingrayPBS1_0"
                    geometry={gltf.nodes.BridgepCube12_BridgeStingrayPBS1_0.geometry}
                    material={gltf.materials.BridgeStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="BridgepCube11">
                  <T.Mesh
                    name="BridgepCube11_BridgeStingrayPBS1_0"
                    geometry={gltf.nodes.BridgepCube11_BridgeStingrayPBS1_0.geometry}
                    material={gltf.materials.BridgeStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="BridgepCube10">
                  <T.Mesh
                    name="BridgepCube10_BridgeStingrayPBS1_0"
                    geometry={gltf.nodes.BridgepCube10_BridgeStingrayPBS1_0.geometry}
                    material={gltf.materials.BridgeStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="BridgepCube9">
                  <T.Mesh
                    name="BridgepCube9_BridgeStingrayPBS1_0"
                    geometry={gltf.nodes.BridgepCube9_BridgeStingrayPBS1_0.geometry}
                    material={gltf.materials.BridgeStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="BridgepCube8">
                  <T.Mesh
                    name="BridgepCube8_BridgeStingrayPBS1_0"
                    geometry={gltf.nodes.BridgepCube8_BridgeStingrayPBS1_0.geometry}
                    material={gltf.materials.BridgeStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="BridgeTop1">
                  <T.Mesh
                    name="BridgeTop1_BridgeStingrayPBS1_0"
                    geometry={gltf.nodes.BridgeTop1_BridgeStingrayPBS1_0.geometry}
                    material={gltf.materials.BridgeStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="BridgepCube2">
                  <T.Mesh
                    name="BridgepCube2_BridgeStingrayPBS1_0"
                    geometry={gltf.nodes.BridgepCube2_BridgeStingrayPBS1_0.geometry}
                    material={gltf.materials.BridgeStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="BridgeTop">
                  <T.Mesh
                    name="BridgeTop_BridgeStingrayPBS1_0"
                    geometry={gltf.nodes.BridgeTop_BridgeStingrayPBS1_0.geometry}
                    material={gltf.materials.BridgeStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="BridgeBottom4">
                  <T.Mesh
                    name="BridgeBottom4_BridgeStingrayPBS2_0"
                    geometry={gltf.nodes.BridgeBottom4_BridgeStingrayPBS2_0.geometry}
                    material={gltf.materials.BridgeStingrayPBS2}
                  />
                </T.Group>
                <T.Group name="BridgeBottom5">
                  <T.Mesh
                    name="BridgeBottom5_BridgeStingrayPBS2_0"
                    geometry={gltf.nodes.BridgeBottom5_BridgeStingrayPBS2_0.geometry}
                    material={gltf.materials.BridgeStingrayPBS2}
                  />
                </T.Group>
                <T.Group name="BridgepPlane1">
                  <T.Group name="BridgepPlane2">
                    <T.Mesh
                      name="BridgepPlane2_Bridgelambert2_0"
                      geometry={gltf.nodes.BridgepPlane2_Bridgelambert2_0.geometry}
                      material={gltf.materials.Bridgelambert2}
                    />
                  </T.Group>
                  <T.Group name="BridgepPlane3">
                    <T.Mesh
                      name="BridgepPlane3_Bridgelambert2_0"
                      geometry={gltf.nodes.BridgepPlane3_Bridgelambert2_0.geometry}
                      material={gltf.materials.Bridgelambert2}
                    />
                  </T.Group>
                  <T.Group name="BridgepPlane4">
                    <T.Mesh
                      name="BridgepPlane4_Bridgelambert2_0"
                      geometry={gltf.nodes.BridgepPlane4_Bridgelambert2_0.geometry}
                      material={gltf.materials.Bridgelambert2}
                    />
                  </T.Group>
                  <T.Mesh
                    name="BridgepPlane1_Bridgelambert2_0"
                    geometry={gltf.nodes.BridgepPlane1_Bridgelambert2_0.geometry}
                    material={gltf.materials.Bridgelambert2}
                  />
                </T.Group>
                <T.Mesh
                  name="BridgeBridge_BridgeStingrayPBS2_0"
                  geometry={gltf.nodes.BridgeBridge_BridgeStingrayPBS2_0.geometry}
                  material={gltf.materials.BridgeStingrayPBS2}
                />
              </T.Group>
              <T.Group name="pPlane7" position={[12.45, -3.93, 0]} scale={[483.87, 485.21, 483.87]}>
                <T.Mesh
                  name="pPlane7_lambert4_0"
                  geometry={gltf.nodes.pPlane7_lambert4_0.geometry}
                  material={gltf.materials.lambert4}
                />
              </T.Group>
              <T.Group name="Rock" position={[-10.44, -3.52, -10.81]} rotation={[-2.76, 0.67, 2.53]} scale={2.28}>
                <T.Group name="RockspCube1" position={[-0.75, -0.48, 0.72]} rotation={[3.11, -0.76, 2.66]}>
                  <T.Mesh
                    name="RockspCube1_RocksStingrayPBS1_0"
                    geometry={gltf.nodes.RockspCube1_RocksStingrayPBS1_0.geometry}
                    material={gltf.materials.RocksStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="pCube4" position={[-2.16, -2.82, 3.93]} rotation={[3.11, -0.76, 2.66]}>
                  <T.Mesh
                    name="pCube4_RocksStingrayPBS1_0"
                    geometry={gltf.nodes.pCube4_RocksStingrayPBS1_0.geometry}
                    material={gltf.materials.RocksStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="pCube1" position={[-1.93, -1.27, 1.98]} rotation={[-2.64, 0.05, 3.06]} scale={1.57}>
                  <T.Mesh
                    name="pCube1_RocksStingrayPBS1_0"
                    geometry={gltf.nodes.pCube1_RocksStingrayPBS1_0.geometry}
                    material={gltf.materials.RocksStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="pCube5" position={[-3.4, -2.13, 3.17]} rotation={[-2.99, -0.38, 2.77]}>
                  <T.Mesh
                    name="pCube5_RocksStingrayPBS1_0"
                    geometry={gltf.nodes.pCube5_RocksStingrayPBS1_0.geometry}
                    material={gltf.materials.RocksStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="pCube6" position={[-2.65, 1.48, -7.46]} rotation={[-2.64, 0.05, 3.06]} scale={1.57}>
                  <T.Mesh
                    name="pCube6_RocksStingrayPBS1_0"
                    geometry={gltf.nodes.pCube6_RocksStingrayPBS1_0.geometry}
                    material={gltf.materials.RocksStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="pCube7" position={[-2.52, 1.23, -10.24]} rotation={[2.93, -1.31, 2.81]} scale={2.37}>
                  <T.Mesh
                    name="pCube7_RocksStingrayPBS1_0"
                    geometry={gltf.nodes.pCube7_RocksStingrayPBS1_0.geometry}
                    material={gltf.materials.RocksStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="pCube8" position={[9.72, -1.05, 9.37]} rotation={[-2.98, -0.97, 3.09]} scale={2.37}>
                  <T.Mesh
                    name="pCube8_RocksStingrayPBS1_0"
                    geometry={gltf.nodes.pCube8_RocksStingrayPBS1_0.geometry}
                    material={gltf.materials.RocksStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="pCube9" position={[10.25, -0.41, 11.6]} rotation={[-2.64, 0.05, 3.06]} scale={1.57}>
                  <T.Mesh
                    name="pCube9_RocksStingrayPBS1_0"
                    geometry={gltf.nodes.pCube9_RocksStingrayPBS1_0.geometry}
                    material={gltf.materials.RocksStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="pCube10" position={[-13.45, -7.24, 6.99]} rotation={[3.11, -0.76, 2.66]}>
                  <T.Mesh
                    name="pCube10_RocksStingrayPBS1_0"
                    geometry={gltf.nodes.pCube10_RocksStingrayPBS1_0.geometry}
                    material={gltf.materials.RocksStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="pCube11" position={[-17.85, -9.84, 7.16]} rotation={[-2.74, -0.33, 2.53]} scale={1.92}>
                  <T.Mesh
                    name="pCube11_RocksStingrayPBS1_0"
                    geometry={gltf.nodes.pCube11_RocksStingrayPBS1_0.geometry}
                    material={gltf.materials.RocksStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="pCube12" position={[-15.35, -8.9, 6.83]} rotation={[0.66, -1.26, 0.08]} scale={2.17}>
                  <T.Mesh
                    name="pCube12_RocksStingrayPBS1_0"
                    geometry={gltf.nodes.pCube12_RocksStingrayPBS1_0.geometry}
                    material={gltf.materials.RocksStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="pCube13" position={[-5.33, 1.15, -12.92]} rotation={[-2.62, -1.25, -2.38]} scale={3.84}>
                  <T.Mesh
                    name="pCube13_RocksStingrayPBS1_0"
                    geometry={gltf.nodes.pCube13_RocksStingrayPBS1_0.geometry}
                    material={gltf.materials.RocksStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="pCube14" position={[-7.51, 0.98, -14.66]} rotation={[2.47, -0.98, 2.94]} scale={2.37}>
                  <T.Mesh
                    name="pCube14_RocksStingrayPBS1_0"
                    geometry={gltf.nodes.pCube14_RocksStingrayPBS1_0.geometry}
                    material={gltf.materials.RocksStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="pCube15" position={[-29.19, -9.45, -5.88]} rotation={[-2.74, -0.33, 2.53]} scale={1.39}>
                  <T.Mesh
                    name="pCube15_RocksStingrayPBS1_0"
                    geometry={gltf.nodes.pCube15_RocksStingrayPBS1_0.geometry}
                    material={gltf.materials.RocksStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="pCube16" position={[-7.25, -10.66, 23]} rotation={[3.1, -1.26, 2.37]} scale={1.61}>
                  <T.Mesh
                    name="pCube16_RocksStingrayPBS1_0"
                    geometry={gltf.nodes.pCube16_RocksStingrayPBS1_0.geometry}
                    material={gltf.materials.RocksStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="pCube25" position={[-3.43, -12.27, 27.38]} rotation={[-2.62, -1.25, -2.38]} scale={3.33}>
                  <T.Mesh
                    name="pCube25_RocksStingrayPBS1_0"
                    geometry={gltf.nodes.pCube25_RocksStingrayPBS1_0.geometry}
                    material={gltf.materials.RocksStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="pCube26" position={[-5.73, -11.43, 27.12]} rotation={[3.1, -1.26, 2.37]} scale={1.61}>
                  <T.Mesh
                    name="pCube26_RocksStingrayPBS1_0"
                    geometry={gltf.nodes.pCube26_RocksStingrayPBS1_0.geometry}
                    material={gltf.materials.RocksStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="pCube27" position={[-4.8, -11.4, 28.11]} rotation={[0.77, -0.81, -0.17]} scale={1.61}>
                  <T.Mesh
                    name="pCube27_RocksStingrayPBS1_0"
                    geometry={gltf.nodes.pCube27_RocksStingrayPBS1_0.geometry}
                    material={gltf.materials.RocksStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="pCube28" position={[-2.3, -12.42, 29.97]} rotation={[0.75, -0.1, 0.37]} scale={2.09}>
                  <T.Mesh
                    name="pCube28_RocksStingrayPBS1_0"
                    geometry={gltf.nodes.pCube28_RocksStingrayPBS1_0.geometry}
                    material={gltf.materials.RocksStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="pCube30" position={[-17.36, -3.54, -12.26]} rotation={[2.47, -0.98, 2.94]} scale={2.37}>
                  <T.Mesh
                    name="pCube30_RocksStingrayPBS1_0"
                    geometry={gltf.nodes.pCube30_RocksStingrayPBS1_0.geometry}
                    material={gltf.materials.RocksStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="pCube31" position={[-19.01, -4.93, -12.42]} rotation={[2.75, 0.79, 2.35]} scale={2.37}>
                  <T.Mesh
                    name="pCube31_RocksStingrayPBS1_0"
                    geometry={gltf.nodes.pCube31_RocksStingrayPBS1_0.geometry}
                    material={gltf.materials.RocksStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="pCube32" position={[7.73, -4.97, 21.17]} rotation={[-2.64, 0.05, 3.06]} scale={1.57}>
                  <T.Mesh
                    name="pCube32_RocksStingrayPBS1_0"
                    geometry={gltf.nodes.pCube32_RocksStingrayPBS1_0.geometry}
                    material={gltf.materials.RocksStingrayPBS1}
                  />
                </T.Group>
                <T.Mesh
                  name="Rock_RocksStingrayPBS1_0"
                  geometry={gltf.nodes.Rock_RocksStingrayPBS1_0.geometry}
                  material={gltf.materials.RocksStingrayPBS1}
                />
              </T.Group>
              <T.Group name="Moon" position={[71.74, 82, 34.75]}>
                <T.Group name="Object_167" rotation={[Math.PI / 2, 0, 0]}>
                  <T.Group name="Object_168" />
                </T.Group>
              </T.Group>
              <T.Group name="KoiKoi" position={[44.74, -3.49, -21.79]} rotation={[0.52, 0.02, 0]} scale={0.46}>
                <T.Group name="KoipCube2" position={[0, 0.85, 2.21]} rotation={[2.99, 0, 0]} scale={[0.15, 1, 1]}>
                  <T.Mesh
                    name="KoipCube2_KoiStingrayPBS1_0"
                    geometry={gltf.nodes.KoipCube2_KoiStingrayPBS1_0.geometry}
                    material={gltf.materials.KoiStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="KoipCube1" position={[0, 3.65, 0]} scale={[0.15, 1, 1]}>
                  <T.Mesh
                    name="KoipCube1_KoiStingrayPBS1_0"
                    geometry={gltf.nodes.KoipCube1_KoiStingrayPBS1_0.geometry}
                    material={gltf.materials.KoiStingrayPBS1}
                  />
                </T.Group>
                <T.Group
                  name="KoiFin1"
                  position={[1.28, 1.34, -2.33]}
                  rotation={[0, 0.7, 0]}
                  scale={[0.11, 0.82, 0.82]}
                >
                  <T.Mesh
                    name="KoiFin1_KoiStingrayPBS1_0"
                    geometry={gltf.nodes.KoiFin1_KoiStingrayPBS1_0.geometry}
                    material={gltf.materials.KoiStingrayPBS1}
                  />
                </T.Group>
                <T.Group
                  name="KoiFin"
                  position={[-1.42, 1.33, -2.33]}
                  rotation={[0, -0.68, 0]}
                  scale={[0.11, 0.82, 0.82]}
                >
                  <T.Mesh
                    name="KoiFin_KoiStingrayPBS1_0"
                    geometry={gltf.nodes.KoiFin_KoiStingrayPBS1_0.geometry}
                    material={gltf.materials.KoiStingrayPBS1}
                  />
                </T.Group>
                <T.Mesh
                  name="KoiKoi_KoiStingrayPBS1_0"
                  geometry={gltf.nodes.KoiKoi_KoiStingrayPBS1_0.geometry}
                  material={gltf.materials.KoiStingrayPBS1}
                />
              </T.Group>
              <T.Group name="Koi1" position={[0.6, 0, -1.55]}>
                <T.Group name="pCube2">
                  <T.Mesh
                    name="pCube2_KoiStingrayPBS1_0"
                    geometry={gltf.nodes.pCube2_KoiStingrayPBS1_0.geometry}
                    material={gltf.materials.KoiStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="pCube1_1">
                  <T.Mesh
                    name="pCube1_KoiStingrayPBS1_0"
                    geometry={gltf.nodes.pCube1_KoiStingrayPBS1_0.geometry}
                    material={gltf.materials.KoiStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="Fin1">
                  <T.Mesh
                    name="Fin1_KoiStingrayPBS1_0"
                    geometry={gltf.nodes.Fin1_KoiStingrayPBS1_0.geometry}
                    material={gltf.materials.KoiStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="Fin">
                  <T.Mesh
                    name="Fin_KoiStingrayPBS1_0"
                    geometry={gltf.nodes.Fin_KoiStingrayPBS1_0.geometry}
                    material={gltf.materials.KoiStingrayPBS1}
                  />
                </T.Group>
                <T.Mesh
                  name="Koi1_KoiStingrayPBS1_0"
                  geometry={gltf.nodes.Koi1_KoiStingrayPBS1_0.geometry}
                  material={gltf.materials.KoiStingrayPBS1}
                />
              </T.Group>
              <T.Group name="Koi2" position={[-47.42, -0.44, 3.75]}>
                <T.Group name="pCube2_1">
                  <T.Mesh
                    name="pCube2_KoiStingrayPBS1_0_1"
                    geometry={gltf.nodes.pCube2_KoiStingrayPBS1_0_1.geometry}
                    material={gltf.materials.KoiStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="pCube1_2">
                  <T.Mesh
                    name="pCube1_KoiStingrayPBS1_0_1"
                    geometry={gltf.nodes.pCube1_KoiStingrayPBS1_0_1.geometry}
                    material={gltf.materials.KoiStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="Fin1_1">
                  <T.Mesh
                    name="Fin1_KoiStingrayPBS1_0_1"
                    geometry={gltf.nodes.Fin1_KoiStingrayPBS1_0_1.geometry}
                    material={gltf.materials.KoiStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="Fin_1">
                  <T.Mesh
                    name="Fin_KoiStingrayPBS1_0_1"
                    geometry={gltf.nodes.Fin_KoiStingrayPBS1_0_1.geometry}
                    material={gltf.materials.KoiStingrayPBS1}
                  />
                </T.Group>
                <T.Mesh
                  name="Koi2_KoiStingrayPBS1_0"
                  geometry={gltf.nodes.Koi2_KoiStingrayPBS1_0.geometry}
                  material={gltf.materials.KoiStingrayPBS1}
                />
              </T.Group>
              <T.Group
                name="Bench1"
                position={[27.24, 5.75, 23.44]}
                rotation={[-3.09, -1.11, -3.1]}
                scale={[1.39, 1.02, 0.84]}
              >
                <T.Group name="BenchpCube19" position={[-3.06, 4.95, -0.01]} scale={[0.26, 1.1, 6.5]}>
                  <T.Mesh
                    name="BenchpCube19_BenchStingrayPBS1_0"
                    geometry={gltf.nodes.BenchpCube19_BenchStingrayPBS1_0.geometry}
                    material={gltf.materials.BenchStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="BenchpCube18" position={[2.92, 4.97, -0.01]} scale={[0.26, 1.1, 6.5]}>
                  <T.Mesh
                    name="BenchpCube18_BenchStingrayPBS1_0"
                    geometry={gltf.nodes.BenchpCube18_BenchStingrayPBS1_0.geometry}
                    material={gltf.materials.BenchStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="BenchpCube17" position={[2.92, -0.46, -0.01]} scale={[0.26, 1.1, 6.5]}>
                  <T.Mesh
                    name="BenchpCube17_BenchStingrayPBS1_0"
                    geometry={gltf.nodes.BenchpCube17_BenchStingrayPBS1_0.geometry}
                    material={gltf.materials.BenchStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="BenchpCube2" position={[-3.06, -0.46, -0.01]} scale={[0.26, 1.1, 6.5]}>
                  <T.Mesh
                    name="BenchpCube2_BenchStingrayPBS1_0"
                    geometry={gltf.nodes.BenchpCube2_BenchStingrayPBS1_0.geometry}
                    material={gltf.materials.BenchStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="Benchpost7" position={[2.95, 2.03, 3.84]} scale={[1, 6.1, 1.26]}>
                  <T.Group name="Benchpost4" position={[0, 0, -5.91]}>
                    <T.Mesh
                      name="Benchpost4_BenchStingrayPBS2_0"
                      geometry={gltf.nodes.Benchpost4_BenchStingrayPBS2_0.geometry}
                      material={gltf.materials.BenchStingrayPBS2}
                    />
                  </T.Group>
                  <T.Group name="Benchpost5" position={[-6, 0, -5.91]}>
                    <T.Mesh
                      name="Benchpost5_BenchStingrayPBS2_0"
                      geometry={gltf.nodes.Benchpost5_BenchStingrayPBS2_0.geometry}
                      material={gltf.materials.BenchStingrayPBS2}
                    />
                  </T.Group>
                  <T.Mesh
                    name="Benchpost7_BenchStingrayPBS2_0"
                    geometry={gltf.nodes.Benchpost7_BenchStingrayPBS2_0.geometry}
                    material={gltf.materials.BenchStingrayPBS2}
                  />
                </T.Group>
                <T.Group name="Benchpost6" position={[2.95, 2.03, 3.84]} scale={[1, 6.1, 1.26]}>
                  <T.Group name="Benchpost4_1" position={[0, 0, -5.91]}>
                    <T.Mesh
                      name="Benchpost4_BenchStingrayPBS2_0_1"
                      geometry={gltf.nodes.Benchpost4_BenchStingrayPBS2_0_1.geometry}
                      material={gltf.materials.BenchStingrayPBS2}
                    />
                  </T.Group>
                  <T.Group name="Benchpost5_1" position={[-6, 0, -5.91]}>
                    <T.Mesh
                      name="Benchpost5_BenchStingrayPBS2_0_1"
                      geometry={gltf.nodes.Benchpost5_BenchStingrayPBS2_0_1.geometry}
                      material={gltf.materials.BenchStingrayPBS2}
                    />
                  </T.Group>
                  <T.Mesh
                    name="Benchpost6_BenchStingrayPBS2_0"
                    geometry={gltf.nodes.Benchpost6_BenchStingrayPBS2_0.geometry}
                    material={gltf.materials.BenchStingrayPBS2}
                  />
                </T.Group>
                <T.Group name="Benchpost3" position={[2.95, 2.03, 3.84]} scale={[1, 6.1, 1.26]}>
                  <T.Group name="Benchpost4_2" position={[0, 0, -5.91]}>
                    <T.Mesh
                      name="Benchpost4_BenchStingrayPBS2_0_2"
                      geometry={gltf.nodes.Benchpost4_BenchStingrayPBS2_0_2.geometry}
                      material={gltf.materials.BenchStingrayPBS2}
                    />
                  </T.Group>
                  <T.Group name="Benchpost5_2" position={[-6, 0, -5.91]}>
                    <T.Mesh
                      name="Benchpost5_BenchStingrayPBS2_0_2"
                      geometry={gltf.nodes.Benchpost5_BenchStingrayPBS2_0_2.geometry}
                      material={gltf.materials.BenchStingrayPBS2}
                    />
                  </T.Group>
                  <T.Group name="Benchpost8" position={[-6, 0, -0.01]}>
                    <T.Mesh
                      name="Benchpost8_BenchStingrayPBS2_0"
                      geometry={gltf.nodes.Benchpost8_BenchStingrayPBS2_0.geometry}
                      material={gltf.materials.BenchStingrayPBS2}
                    />
                  </T.Group>
                  <T.Mesh
                    name="Benchpost3_BenchStingrayPBS2_0"
                    geometry={gltf.nodes.Benchpost3_BenchStingrayPBS2_0.geometry}
                    material={gltf.materials.BenchStingrayPBS2}
                  />
                </T.Group>
                <T.Group
                  name="BenchpCube4"
                  position={[0, 5.44, 3.85]}
                  rotation={[Math.PI, 0, 0]}
                  scale={[-10.41, -0.77, -0.8]}
                >
                  <T.Group name="BenchpCube12" position={[0, 0, -9.36]}>
                    <T.Mesh
                      name="BenchpCube12_BenchStingrayPBS1_0"
                      geometry={gltf.nodes.BenchpCube12_BenchStingrayPBS1_0.geometry}
                      material={gltf.materials.BenchStingrayPBS1}
                    />
                  </T.Group>
                  <T.Group name="BenchpCube13" position={[0, 0, -7.55]}>
                    <T.Mesh
                      name="BenchpCube13_BenchStingrayPBS1_0"
                      geometry={gltf.nodes.BenchpCube13_BenchStingrayPBS1_0.geometry}
                      material={gltf.materials.BenchStingrayPBS1}
                    />
                  </T.Group>
                  <T.Group name="BenchpCube14" position={[0, 0, -5.7]}>
                    <T.Mesh
                      name="BenchpCube14_BenchStingrayPBS1_0"
                      geometry={gltf.nodes.BenchpCube14_BenchStingrayPBS1_0.geometry}
                      material={gltf.materials.BenchStingrayPBS1}
                    />
                  </T.Group>
                  <T.Group name="BenchpCube15" position={[0, 0, -3.74]}>
                    <T.Mesh
                      name="BenchpCube15_BenchStingrayPBS1_0"
                      geometry={gltf.nodes.BenchpCube15_BenchStingrayPBS1_0.geometry}
                      material={gltf.materials.BenchStingrayPBS1}
                    />
                  </T.Group>
                  <T.Group name="BenchpCube16" position={[0, 0, -1.84]}>
                    <T.Mesh
                      name="BenchpCube16_BenchStingrayPBS1_0"
                      geometry={gltf.nodes.BenchpCube16_BenchStingrayPBS1_0.geometry}
                      material={gltf.materials.BenchStingrayPBS1}
                    />
                  </T.Group>
                  <T.Mesh
                    name="BenchpCube4_BenchStingrayPBS1_0"
                    geometry={gltf.nodes.BenchpCube4_BenchStingrayPBS1_0.geometry}
                    material={gltf.materials.BenchStingrayPBS1}
                  />
                </T.Group>
                <T.Mesh
                  name="Bench1_BenchStingrayPBS1_0"
                  geometry={gltf.nodes.Bench1_BenchStingrayPBS1_0.geometry}
                  material={gltf.materials.BenchStingrayPBS1}
                />
              </T.Group>
              <T.Group
                name="Bamboo1"
                position={[-3.71, 8.82, -0.25]}
                rotation={[-0.11, 1.29, 0.08]}
                scale={[0.71, 5.46, 1]}
              >
                <T.Group
                  name="BamboopCylinder1"
                  position={[1, -0.62, 2.11]}
                  rotation={[0.55, -1.13, 0.5]}
                  scale={[0.73, 1.03, 1.33]}
                >
                  <T.Mesh
                    name="BamboopCylinder1_BambooStingrayPBS2_0"
                    geometry={gltf.nodes.BamboopCylinder1_BambooStingrayPBS2_0.geometry}
                    material={gltf.materials.BambooStingrayPBS2}
                  />
                </T.Group>
                <T.Group
                  name="pCylinder1"
                  position={[-34.97, 0.25, -2.28]}
                  rotation={[0.55, -1.13, 0.5]}
                  scale={[0.73, 1.03, 1.33]}
                >
                  <T.Mesh
                    name="pCylinder1_BambooStingrayPBS2_0"
                    geometry={gltf.nodes.pCylinder1_BambooStingrayPBS2_0.geometry}
                    material={gltf.materials.BambooStingrayPBS2}
                  />
                </T.Group>
                <T.Group
                  name="pCylinder2_3"
                  position={[-33.74, -0.25, 0.47]}
                  rotation={[1.36, -1.32, 1.28]}
                  scale={[0.73, 1.03, 1.33]}
                >
                  <T.Mesh
                    name="pCylinder2_BambooStingrayPBS2_0"
                    geometry={gltf.nodes.pCylinder2_BambooStingrayPBS2_0.geometry}
                    material={gltf.materials.BambooStingrayPBS2}
                  />
                </T.Group>
                <T.Group
                  name="pCylinder3_4"
                  position={[-49.16, -1.5, 46.44]}
                  rotation={[1.36, -1.32, 1.28]}
                  scale={[0.73, 1.03, 1.33]}
                >
                  <T.Mesh
                    name="pCylinder3_BambooStingrayPBS2_0"
                    geometry={gltf.nodes.pCylinder3_BambooStingrayPBS2_0.geometry}
                    material={gltf.materials.BambooStingrayPBS2}
                  />
                </T.Group>
                <T.Group
                  name="pCylinder4"
                  position={[-38.87, -1.94, 50.14]}
                  rotation={[0.18, -0.62, 0.21]}
                  scale={[0.42, 0.58, 0.76]}
                >
                  <T.Mesh
                    name="pCylinder4_BambooStingrayPBS2_0"
                    geometry={gltf.nodes.pCylinder4_BambooStingrayPBS2_0.geometry}
                    material={gltf.materials.BambooStingrayPBS2}
                  />
                </T.Group>
                <T.Group
                  name="pCylinder5"
                  position={[42.78, -1.13, 28.08]}
                  rotation={[1.36, -1.32, 1.28]}
                  scale={[0.73, 1.03, 1.33]}
                >
                  <T.Mesh
                    name="pCylinder5_BambooStingrayPBS2_0"
                    geometry={gltf.nodes.pCylinder5_BambooStingrayPBS2_0.geometry}
                    material={gltf.materials.BambooStingrayPBS2}
                  />
                </T.Group>
                <T.Group
                  name="pCylinder6"
                  position={[44.33, -1.65, 31.61]}
                  rotation={[0.3, -0.87, 0.29]}
                  scale={[0.73, 1.03, 1.33]}
                >
                  <T.Mesh
                    name="pCylinder6_BambooStingrayPBS2_0"
                    geometry={gltf.nodes.pCylinder6_BambooStingrayPBS2_0.geometry}
                    material={gltf.materials.BambooStingrayPBS2}
                  />
                </T.Group>
                <T.Group
                  name="pCylinder7"
                  position={[46.57, -0.63, 28.81]}
                  rotation={[0.3, -0.87, 0.29]}
                  scale={[0.73, 1.03, 1.33]}
                >
                  <T.Mesh
                    name="pCylinder7_BambooStingrayPBS2_0"
                    geometry={gltf.nodes.pCylinder7_BambooStingrayPBS2_0.geometry}
                    material={gltf.materials.BambooStingrayPBS2}
                  />
                </T.Group>
                <T.Group
                  name="pCylinder8"
                  position={[70.13, -0.53, -15.13]}
                  rotation={[0.3, -0.87, 0.29]}
                  scale={[0.73, 1.03, 1.33]}
                >
                  <T.Mesh
                    name="pCylinder8_BambooStingrayPBS2_0"
                    geometry={gltf.nodes.pCylinder8_BambooStingrayPBS2_0.geometry}
                    material={gltf.materials.BambooStingrayPBS2}
                  />
                </T.Group>
                <T.Mesh
                  name="Bamboo1_BambooStingrayPBS2_0"
                  geometry={gltf.nodes.Bamboo1_BambooStingrayPBS2_0.geometry}
                  material={gltf.materials.BambooStingrayPBS2}
                />
              </T.Group>
              <T.Group name="Lily1">
                <T.Group name="pCylinder11">
                  <T.Mesh
                    name="pCylinder11_LilyStingrayPBS1_0"
                    geometry={gltf.nodes.pCylinder11_LilyStingrayPBS1_0.geometry}
                    material={gltf.materials.LilyStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="pCylinder10">
                  <T.Mesh
                    name="pCylinder10_LilyStingrayPBS1_0"
                    geometry={gltf.nodes.pCylinder10_LilyStingrayPBS1_0.geometry}
                    material={gltf.materials.LilyStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="pCylinder9">
                  <T.Mesh
                    name="pCylinder9_LilyStingrayPBS1_0"
                    geometry={gltf.nodes.pCylinder9_LilyStingrayPBS1_0.geometry}
                    material={gltf.materials.LilyStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="pCylinder1_1">
                  <T.Mesh
                    name="pCylinder1_LilyStingrayPBS1_0"
                    geometry={gltf.nodes.pCylinder1_LilyStingrayPBS1_0.geometry}
                    material={gltf.materials.LilyStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="LilypCylinder1">
                  <T.Mesh
                    name="LilypCylinder1_LilyStingrayPBS1_0"
                    geometry={gltf.nodes.LilypCylinder1_LilyStingrayPBS1_0.geometry}
                    material={gltf.materials.LilyStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="pCylinder12">
                  <T.Mesh
                    name="pCylinder12_LilyStingrayPBS1_0"
                    geometry={gltf.nodes.pCylinder12_LilyStingrayPBS1_0.geometry}
                    material={gltf.materials.LilyStingrayPBS1}
                  />
                </T.Group>
                <T.Mesh
                  name="Lily1_LilyStingrayPBS1_0"
                  geometry={gltf.nodes.Lily1_LilyStingrayPBS1_0.geometry}
                  material={gltf.materials.LilyStingrayPBS1}
                />
              </T.Group>
              <T.Group
                name="deerscarepCube1"
                position={[9.26, 1.16, -35.09]}
                rotation={[-Math.PI, -0.79, -Math.PI]}
                scale={[1.24, 1.34, 1.24]}
              >
                <T.Group
                  name="deerscaredeerscarepCylinder4"
                  position={[0, 4.03, 2.21]}
                  rotation={[-2.41, -0.07, -0.01]}
                  scale={[0.53, 3.66, 0.48]}
                >
                  <T.Mesh
                    name="deerscaredeerscarepCylinder4_deerscareStingrayPBS5_0"
                    geometry={gltf.nodes.deerscaredeerscarepCylinder4_deerscareStingrayPBS5_0.geometry}
                    material={gltf.materials.deerscareStingrayPBS5}
                  />
                </T.Group>
                <T.Group
                  name="deerscarepCylinder4"
                  position={[-1.35, 6.87, 2.89]}
                  rotation={[-1.49, 0.07, 0.86]}
                  scale={[0.16, 1.12, 0.13]}
                >
                  <T.Mesh
                    name="deerscarepCylinder4_deerscareStingrayPBS5_0"
                    geometry={gltf.nodes.deerscarepCylinder4_deerscareStingrayPBS5_0.geometry}
                    material={gltf.materials.deerscareStingrayPBS5}
                  />
                </T.Group>
                <T.Group
                  name="deerscarepCylinder3"
                  position={[0.57, 3.33, 2.56]}
                  rotation={[2.75, -0.68, -1.65]}
                  scale={[0.2, 1.57, 0.2]}
                >
                  <T.Mesh
                    name="deerscarepCylinder3_deerscareStingrayPBS5_0"
                    geometry={gltf.nodes.deerscarepCylinder3_deerscareStingrayPBS5_0.geometry}
                    material={gltf.materials.deerscareStingrayPBS5}
                  />
                </T.Group>
                <T.Group name="deerscarepCylinder2" position={[-2.25, 3.78, 2.19]} scale={[0.39, 3.43, 0.39]}>
                  <T.Mesh
                    name="deerscarepCylinder2_deerscareStingrayPBS5_0"
                    geometry={gltf.nodes.deerscarepCylinder2_deerscareStingrayPBS5_0.geometry}
                    material={gltf.materials.deerscareStingrayPBS5}
                  />
                </T.Group>
                <T.Group name="deerscaredeerscarepCylinder2" position={[2.28, 2.21, 2.19]} scale={[0.39, 2.12, 0.39]}>
                  <T.Mesh
                    name="deerscaredeerscarepCylinder2_deerscareStingrayPBS5_0"
                    geometry={gltf.nodes.deerscaredeerscarepCylinder2_deerscareStingrayPBS5_0.geometry}
                    material={gltf.materials.deerscareStingrayPBS5}
                  />
                </T.Group>
                <T.Group name="deerscaredeerscarepCylinder5" position={[0, 0.53, 4.7]} scale={[1.82, 0.12, 1.82]}>
                  <T.Mesh
                    name="deerscaredeerscarepCylinder5_deerscareStingrayPBS5_0"
                    geometry={gltf.nodes.deerscaredeerscarepCylinder5_deerscareStingrayPBS5_0.geometry}
                    material={gltf.materials.deerscareStingrayPBS5}
                  />
                </T.Group>
                <T.Group name="deerscarepCylinder1" position={[0, 0.5, 4.63]} scale={[1.8, 0.08, 1.74]}>
                  <T.Mesh
                    name="deerscarepCylinder1_deerscarelambert2_0"
                    geometry={gltf.nodes.deerscarepCylinder1_deerscarelambert2_0.geometry}
                    material={gltf.materials.deerscarelambert2}
                  />
                </T.Group>
                <T.Mesh
                  name="deerscarepCube1_deerscareStingrayPBS1_0"
                  geometry={gltf.nodes.deerscarepCube1_deerscareStingrayPBS1_0.geometry}
                  material={gltf.materials.deerscareStingrayPBS1}
                />
              </T.Group>
              <T.Group name="CattailCatTail">
                <T.Group name="CattailpCylinder2">
                  <T.Mesh
                    name="CattailpCylinder2_CattailStingrayPBS1_0"
                    geometry={gltf.nodes.CattailpCylinder2_CattailStingrayPBS1_0.geometry}
                    material={gltf.materials.CattailStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="CattailpCylinder1">
                  <T.Mesh
                    name="CattailpCylinder1_CattailStingrayPBS1_0"
                    geometry={gltf.nodes.CattailpCylinder1_CattailStingrayPBS1_0.geometry}
                    material={gltf.materials.CattailStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="CattailpSphere2">
                  <T.Mesh
                    name="CattailpSphere2_CattailStingrayPBS1_0"
                    geometry={gltf.nodes.CattailpSphere2_CattailStingrayPBS1_0.geometry}
                    material={gltf.materials.CattailStingrayPBS1}
                  />
                </T.Group>
                <T.Mesh
                  name="CattailCatTail_CattailStingrayPBS1_0"
                  geometry={gltf.nodes.CattailCatTail_CattailStingrayPBS1_0.geometry}
                  material={gltf.materials.CattailStingrayPBS1}
                />
              </T.Group>
              <T.Group name="CatTail">
                <T.Group name="pCylinder2_4">
                  <T.Mesh
                    name="pCylinder2_CattailStingrayPBS1_0"
                    geometry={gltf.nodes.pCylinder2_CattailStingrayPBS1_0.geometry}
                    material={gltf.materials.CattailStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="pCylinder1_2">
                  <T.Mesh
                    name="pCylinder1_CattailStingrayPBS1_0"
                    geometry={gltf.nodes.pCylinder1_CattailStingrayPBS1_0.geometry}
                    material={gltf.materials.CattailStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="pSphere2_3">
                  <T.Mesh
                    name="pSphere2_CattailStingrayPBS1_0"
                    geometry={gltf.nodes.pSphere2_CattailStingrayPBS1_0.geometry}
                    material={gltf.materials.CattailStingrayPBS1}
                  />
                </T.Group>
                <T.Mesh
                  name="CatTail_CattailStingrayPBS1_0"
                  geometry={gltf.nodes.CatTail_CattailStingrayPBS1_0.geometry}
                  material={gltf.materials.CattailStingrayPBS1}
                />
              </T.Group>
              <T.Group name="CatTail1">
                <T.Group name="pCylinder2_5">
                  <T.Mesh
                    name="pCylinder2_CattailStingrayPBS1_0_1"
                    geometry={gltf.nodes.pCylinder2_CattailStingrayPBS1_0_1.geometry}
                    material={gltf.materials.CattailStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="pCylinder1_3">
                  <T.Mesh
                    name="pCylinder1_CattailStingrayPBS1_0_1"
                    geometry={gltf.nodes.pCylinder1_CattailStingrayPBS1_0_1.geometry}
                    material={gltf.materials.CattailStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="pSphere2_4">
                  <T.Mesh
                    name="pSphere2_CattailStingrayPBS1_0_1"
                    geometry={gltf.nodes.pSphere2_CattailStingrayPBS1_0_1.geometry}
                    material={gltf.materials.CattailStingrayPBS1}
                  />
                </T.Group>
                <T.Mesh
                  name="CatTail1_CattailStingrayPBS1_0"
                  geometry={gltf.nodes.CatTail1_CattailStingrayPBS1_0.geometry}
                  material={gltf.materials.CattailStingrayPBS1}
                />
              </T.Group>
              <T.Group name="Tree_Petals">
                <T.Group name="pPlane16">
                  <T.Mesh
                    name="pPlane16_lambert5_0"
                    geometry={gltf.nodes.pPlane16_lambert5_0.geometry}
                    material={gltf.materials.lambert5}
                  />
                </T.Group>
                <T.Group name="pPlane15">
                  <T.Mesh
                    name="pPlane15_lambert5_0"
                    geometry={gltf.nodes.pPlane15_lambert5_0.geometry}
                    material={gltf.materials.lambert5}
                  />
                </T.Group>
                <T.Group name="pPlane14">
                  <T.Mesh
                    name="pPlane14_lambert5_0"
                    geometry={gltf.nodes.pPlane14_lambert5_0.geometry}
                    material={gltf.materials.lambert5}
                  />
                </T.Group>
                <T.Group name="pPlane13">
                  <T.Mesh
                    name="pPlane13_lambert5_0"
                    geometry={gltf.nodes.pPlane13_lambert5_0.geometry}
                    material={gltf.materials.lambert5}
                  />
                </T.Group>
                <T.Group name="pPlane12">
                  <T.Mesh
                    name="pPlane12_lambert5_0"
                    geometry={gltf.nodes.pPlane12_lambert5_0.geometry}
                    material={gltf.materials.lambert5}
                  />
                </T.Group>
                <T.Group name="pPlane11">
                  <T.Mesh
                    name="pPlane11_lambert5_0"
                    geometry={gltf.nodes.pPlane11_lambert5_0.geometry}
                    material={gltf.materials.lambert5}
                  />
                </T.Group>
                <T.Group name="pPlane10">
                  <T.Mesh
                    name="pPlane10_lambert5_0"
                    geometry={gltf.nodes.pPlane10_lambert5_0.geometry}
                    material={gltf.materials.lambert5}
                  />
                </T.Group>
                <T.Group name="pPlane19">
                  <T.Mesh
                    name="pPlane19_lambert5_0"
                    geometry={gltf.nodes.pPlane19_lambert5_0.geometry}
                    material={gltf.materials.lambert5}
                  />
                </T.Group>
                <T.Mesh
                  name="Tree_Petals_lambert5_0"
                  geometry={gltf.nodes.Tree_Petals_lambert5_0.geometry}
                  material={gltf.materials.lambert5}
                />
              </T.Group>
              <T.Group name="bottom" position={[0, -1000.1, 0]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                <T.Group name="Object_349" />
              </T.Group>
              <T.Group
                name="Island_2"
                position={[15.61, -2.08, -37.54]}
                rotation={[0, -1.56, 0]}
                scale={[29.51, 6.52, 49.35]}
              >
                <T.Mesh
                  name="Island_2_StingrayPBS2_0"
                  geometry={gltf.nodes.Island_2_StingrayPBS2_0.geometry}
                  material={gltf.materials.StingrayPBS2}
                />
              </T.Group>
              <T.Group name="Koi3" position={[44.74, -3.49, -0.39]} rotation={[0.52, 0.83, -0.31]} scale={0.46}>
                <T.Group name="pCube2_2" position={[0, 0.85, 2.21]} rotation={[2.99, 0, 0]} scale={[0.15, 1, 1]}>
                  <T.Mesh
                    name="pCube2_KoiStingrayPBS1_0_2"
                    geometry={gltf.nodes.pCube2_KoiStingrayPBS1_0_2.geometry}
                    material={gltf.materials.KoiStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="pCube1_3" position={[0, 3.65, 0]} scale={[0.15, 1, 1]}>
                  <T.Mesh
                    name="pCube1_KoiStingrayPBS1_0_2"
                    geometry={gltf.nodes.pCube1_KoiStingrayPBS1_0_2.geometry}
                    material={gltf.materials.KoiStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="Fin1_2" position={[1.28, 1.34, -2.33]} rotation={[0, 0.7, 0]} scale={[0.11, 0.82, 0.82]}>
                  <T.Mesh
                    name="Fin1_KoiStingrayPBS1_0_2"
                    geometry={gltf.nodes.Fin1_KoiStingrayPBS1_0_2.geometry}
                    material={gltf.materials.KoiStingrayPBS1}
                  />
                </T.Group>
                <T.Group
                  name="Fin_2"
                  position={[-1.42, 1.33, -2.33]}
                  rotation={[0, -0.68, 0]}
                  scale={[0.11, 0.82, 0.82]}
                >
                  <T.Mesh
                    name="Fin_KoiStingrayPBS1_0_2"
                    geometry={gltf.nodes.Fin_KoiStingrayPBS1_0_2.geometry}
                    material={gltf.materials.KoiStingrayPBS1}
                  />
                </T.Group>
                <T.Mesh
                  name="Koi3_KoiStingrayPBS1_0"
                  geometry={gltf.nodes.Koi3_KoiStingrayPBS1_0.geometry}
                  material={gltf.materials.KoiStingrayPBS1}
                />
              </T.Group>
              <T.Group name="CatTail2">
                <T.Group name="pCylinder2_6">
                  <T.Mesh
                    name="pCylinder2_CattailStingrayPBS1_0_2"
                    geometry={gltf.nodes.pCylinder2_CattailStingrayPBS1_0_2.geometry}
                    material={gltf.materials.CattailStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="pCylinder1_4">
                  <T.Mesh
                    name="pCylinder1_CattailStingrayPBS1_0_2"
                    geometry={gltf.nodes.pCylinder1_CattailStingrayPBS1_0_2.geometry}
                    material={gltf.materials.CattailStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="pSphere2_5">
                  <T.Mesh
                    name="pSphere2_CattailStingrayPBS1_0_2"
                    geometry={gltf.nodes.pSphere2_CattailStingrayPBS1_0_2.geometry}
                    material={gltf.materials.CattailStingrayPBS1}
                  />
                </T.Group>
                <T.Mesh
                  name="CatTail2_CattailStingrayPBS1_0"
                  geometry={gltf.nodes.CatTail2_CattailStingrayPBS1_0.geometry}
                  material={gltf.materials.CattailStingrayPBS1}
                />
              </T.Group>
              <T.Group name="Koi4" position={[14.91, 0, 53.89]}>
                <T.Group name="pCube2_3">
                  <T.Mesh
                    name="pCube2_KoiStingrayPBS1_0_3"
                    geometry={gltf.nodes.pCube2_KoiStingrayPBS1_0_3.geometry}
                    material={gltf.materials.KoiStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="pCube1_4">
                  <T.Mesh
                    name="pCube1_KoiStingrayPBS1_0_3"
                    geometry={gltf.nodes.pCube1_KoiStingrayPBS1_0_3.geometry}
                    material={gltf.materials.KoiStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="Fin1_3">
                  <T.Mesh
                    name="Fin1_KoiStingrayPBS1_0_3"
                    geometry={gltf.nodes.Fin1_KoiStingrayPBS1_0_3.geometry}
                    material={gltf.materials.KoiStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="Fin_3">
                  <T.Mesh
                    name="Fin_KoiStingrayPBS1_0_3"
                    geometry={gltf.nodes.Fin_KoiStingrayPBS1_0_3.geometry}
                    material={gltf.materials.KoiStingrayPBS1}
                  />
                </T.Group>
                <T.Mesh
                  name="Koi4_KoiStingrayPBS1_0"
                  geometry={gltf.nodes.Koi4_KoiStingrayPBS1_0.geometry}
                  material={gltf.materials.KoiStingrayPBS1}
                />
              </T.Group>
              <T.Group name="Koi5" position={[44.74, -7.08, 87.67]} rotation={[0.52, 0.83, -0.31]} scale={0.73}>
                <T.Group name="pCube2_4" position={[0, 0.85, 2.21]} rotation={[2.99, 0, 0]} scale={[0.15, 1, 1]}>
                  <T.Mesh
                    name="pCube2_KoiStingrayPBS1_0_4"
                    geometry={gltf.nodes.pCube2_KoiStingrayPBS1_0_4.geometry}
                    material={gltf.materials.KoiStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="pCube1_5" position={[0, 3.65, 0]} scale={[0.15, 1, 1]}>
                  <T.Mesh
                    name="pCube1_KoiStingrayPBS1_0_4"
                    geometry={gltf.nodes.pCube1_KoiStingrayPBS1_0_4.geometry}
                    material={gltf.materials.KoiStingrayPBS1}
                  />
                </T.Group>
                <T.Group name="Fin1_4" position={[1.28, 1.34, -2.33]} rotation={[0, 0.7, 0]} scale={[0.11, 0.82, 0.82]}>
                  <T.Mesh
                    name="Fin1_KoiStingrayPBS1_0_4"
                    geometry={gltf.nodes.Fin1_KoiStingrayPBS1_0_4.geometry}
                    material={gltf.materials.KoiStingrayPBS1}
                  />
                </T.Group>
                <T.Group
                  name="Fin_4"
                  position={[-1.42, 1.33, -2.33]}
                  rotation={[0, -0.68, 0]}
                  scale={[0.11, 0.82, 0.82]}
                >
                  <T.Mesh
                    name="Fin_KoiStingrayPBS1_0_4"
                    geometry={gltf.nodes.Fin_KoiStingrayPBS1_0_4.geometry}
                    material={gltf.materials.KoiStingrayPBS1}
                  />
                </T.Group>
                <T.Mesh
                  name="Koi5_KoiStingrayPBS1_0"
                  geometry={gltf.nodes.Koi5_KoiStingrayPBS1_0.geometry}
                  material={gltf.materials.KoiStingrayPBS1}
                />
              </T.Group>
              <T.Group name="pPlane20" position={[12.14, -11.22, -0.17]} scale={[483.87, 485.21, 483.87]}>
                <T.Mesh
                  name="pPlane20_lambert4_0"
                  geometry={gltf.nodes.pPlane20_lambert4_0.geometry}
                  material={gltf.materials.lambert4}
                />
              </T.Group>
            </T.Group>
          </T.Group>
        </T.Group>
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
